version: '3.8'

services:
  app:
    build: .
    container_name: virtual-bank-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/virtual_bank
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: virtual-bank-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: virtual_bank
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
